### PR TITLE
Corrections to IBM i LSAM Job Tracking and Queuing

### PR DESCRIPTION
**Pull request by GLooseJr**
Corrected description of how to use OpCon schedules with Job Tracking, adding notes about the AdHoc schedule.  Also replaced the link to IBM i Agent information to branch directly into the IBM i Agent online help chapter about Job Tracking.  The $JOB:QUEUED event type was also updated with similar corrections.

### CODE REVIEW

**Review by cary-lewis — DISMISSED** [review]
Approve

**Review by rweesner — APPROVED** [review]

**Comment by GLooseJr** [comment]
Roy,

I’ve seen two approval cycles, and I see that Ryan deleted my branch, but I’m not seeing the updates in the published version of opcon-docs.

This is my first time trying to update the core products document.  Are there steps I’m still waiting for?

Thanks,
George


George Loose
Technical Product Manager
Office: 281.446.5000 | Direct: 281.312.6649
www.SMAtechnologies.com
| ***@***.***
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
Signature For George Loose

**Comment by rweesner** [comment]
Hi George,

We needed to remove the yarn.lock file from your push, as it is not in-sync with our remote version. Your changes to the primary file are being pushed through now and should be live in a few minutes. Ryan has asked that when you do a future push to opcon-docs, to only push changed documentation files (.md and image files) and remove any ancillary yarn files from the push upstream.
(That issue is really on me for asking you to change the yarn.lock file locally in order to complete the install on your new drive. It shouldn’t be an issue going forward).


-Roy


Roy Weesner
Education Manager
Office: 281.446.5000 | Support: 877.363.2305
www.SMAtechnologies.com
| ***@***.***
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
Signature For Roy Weesner
From: George Loose ***@***.***>
Date: Monday, February 6, 2023 at 4:51 PM
To: smatechnologies/opcon-docs ***@***.***>
Cc: Roy Weesner ***@***.***>, Mention ***@***.***>
Subject: Re: [smatechnologies/opcon-docs] Corrections to IBM i LSAM Job Tracking and Queuing (PR #134)
CAUTION: This email originated outside of SMA. Do not click links or open attachments unless you know the content is safe.

________________________________
Roy,

I’ve seen two approval cycles, and I see that Ryan deleted my branch, but I’m not seeing the updates in the published version of opcon-docs.

This is my first time trying to update the core products document. Are there steps I’m still waiting for?

Thanks,
George


George Loose
Technical Product Manager
Office: 281.446.5000 | Direct: 281.312.6649
www.SMAtechnologies.com<http://www.SMAtechnologies.com>
| ***@***.***
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
Signature For George Loose

**Comment by GLooseJr** [comment]
Roy,

Thanks for the update.

I’m concerned that the auxiliary tools configurations that get checked out with a document release are out of sync.  It seems to me that if I had to re-install them to get them in sync, then the next person who checks out this same document may be out of sync as well.  But I don’t know the details of how the yarn.lock file works.  So I can avoid committing changes to the tools in the future.  However, this does detract from the simplicity of the VS Code tools for repository management.

Thanks for the support!
George

**Pull request merged**
